---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: work-deployment
  labels:
    app: react-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - image: sassisam/reactapp
        name: react-app
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: work-service
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 3050
      targetPort: 3000
      nodePort: 32004
