apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 8081
      targetPort: 8081
  selector:
    app: mongo-express
